### ISSUE TITLE
Authentication Gitlab 

### ISSUE THREAD

**Issue by Daxcor69** [bitnami/bitnami-docker-git#2]
I am using the bitnami/nginx helm chart to deploy on to a k8s cluster. There was a bug and it was fixed. The bug was with using a git repo for the static content for the nginx container.  That has been fixed and works fine, however I seem to be encountering a authentication issue.  I have a PRIVATE repo on gitlab for the website.  This is the repo I wish the helm chart to pull from.  I don't see in the values.yaml a way to provide credentials to the bitnami/git image specified in the helm chart.

```
cloneStaticSiteFromGit:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/git
    tag: 2.28.0-debian-10-r57
    pullPolicy: IfNotPresent
  repository: https://gitlab.com/bradley8/website-v2.git
  branch: master
  interval: 60

```

It feels like I am missing something really obvious so I am a little bit embarrassed to ask this question but I am stumped.  I noticed that it references a different image name   bitnami/git   instead of this image bitnami/bitnami-docker-git.  Any  help would be greatly appreciated.

Thanks.
